name: Tex systems
favicon: null
layout_spectrum: 0.90655
typography_spectrum: 0.00293
title: Vokiški dažai namams ir ne tik
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b7fe00'
    - '#016100'
    - '#fe0000'
    - '#d66c00'
    - '#00e301'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
