name: Tex systems
favicon: null
layout_spectrum: 0.15703
typography_spectrum: 0.47885
title: Vokiški dažai
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a79c88'
    - '#786b5a'
    - '#e4e1d2'
    - '#55473a'
    - '#2d221c'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
