name: Tex systems
favicon: null
layout_spectrum: 1
typography_spectrum: 0.37969
title: Tex systems
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00a0db'
    - '#fbf558'
    - '#e88e3c'
    - '#e70022'
    - '#0000ff'
  brandStrength: 1
  lightness: 0.49874228332191706
  saturation: 0.21081248321570456
  rhythmicContrast: 0.8642976523842663
purpose: []
