name: Tex systems
favicon: null
layout_spectrum: 0.24521
typography_spectrum: 0.37969
title: Tex systems
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00a0db'
    - '#fbf558'
    - '#e88e3c'
    - '#e70022'
    - '#0000ff'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.2108124832157046
  rhythmicContrast: 1
purpose: []
