title: Tex systems
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2108124832157046
  brandStrength: 1
  lightness: 0.4987422833219171
  brandColors:
    - '#00a0db'
    - '#fbf558'
    - '#e88e3c'
    - '#e70022'
    - '#0000ff'
  rhythmicContrast: 0.8642976523842663
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Tex systems
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.37969
layout_spectrum: 1
